# for chords
GRID_XS = [907, 769, 630, 492, 354, 216]
GRID_YS = [413, 561, 719, 877, 1045]

STATUS_Y = 280
SHIFT_FINGERS = 53
SHIFT_STRINGS = 29

NAME_CORDS = (200, 10)
NAME_SIZE = (900, 300)

FONT_FILE = 'ARLRDBD.TTF'
FONT_SIZE = 224
FONT_SMALL_SIZE = 120

KEY_WORDS = ('no', 'maj', 'sus', 'add')

DISPLAY_SIZE = (238, 278)


# for arrows
MASSIVE_SIZE = 16

PICTURE_WIDTH = 650
PICTURE_HEIGHT = 210
PICTURE_SIZE = (PICTURE_WIDTH, PICTURE_HEIGHT)

ARROW_HEIGHT = 447
ARROW_WIDTH = 307
ARROW_SIZE = (ARROW_WIDTH, ARROW_HEIGHT)

DISTANCE_BETWEEN_ARROWS = 100

ORIGINAL_SIZE = (DISTANCE_BETWEEN_ARROWS + MASSIVE_SIZE * (ARROW_WIDTH + DISTANCE_BETWEEN_ARROWS), 3 * ARROW_HEIGHT)

COMPRESSION_RATIO_BY_WIDTH = 1  # лучше не делать < 0.12
COMPRESSION_RATIO_BY_HEIGHT = 1  # лучше не делать < 0.16
COMPRESSION_RATIO = (COMPRESSION_RATIO_BY_WIDTH, COMPRESSION_RATIO_BY_HEIGHT)

NAME_ARROWS = "./arrows/arrows.png"
NAME_HIDE_ARROWS = "./arrows/hide.png"
NAME_ARROW_WIDGET = "./src/tmp/arrows.png"
NAME_COPY_ARROW_WIDGET = "./src/tmp/copy_arrows.png"
PATH_ARROWS = "./arrows/"
PATH_HIDE_ARROWS = "./arrows/hide_"
PATH_ARROWS_WIDGET = "./src/arrows/"