# universal
BASE_FONT_FILE = 'ARLRDBD.TTF'
BASE_FONT_DIR = f"./src/fonts/{BASE_FONT_FILE}"

ADDITIONAL_FONT_FILE = 'TAHOMABD.TTF'
ADDITIONAL_FONT_DIR = f"./src/fonts/{ADDITIONAL_FONT_FILE}"

BASE_FONT_SIZE = 224
BASE_FONT_SMALL_SIZE = 120

ADDITIONAL_FONT_SIZE = 192
ADDITIONAL_FONT_SMALL_SIZE = 98

# for paint
TRANSPARENT = (255, 255, 255, 0)

# DEFAULT_TMP_IMAGE_DIR = "tmp/default_image.png"
DEFAULT_DRAFT_DIR = "tmp/final_images/default_finale.png"


# for chords
GRID_XS = [907, 769, 630, 492, 354, 216]
GRID_YS = [413, 561, 719, 877, 1045]

CHORD_IMAGE_WIDTH = 1000
CHORD_IMAGE_HEIGHT = 1240
CHORD_IMAGE_SIZE = (CHORD_IMAGE_WIDTH, CHORD_IMAGE_HEIGHT)

STATUS_Y = 280
SHIFT_FINGERS = 53
SHIFT_STRINGS = 29

BARRES = (224, 382, 520, 658, 784, 796)
FINGER_SIZE = (106, 106)
STATE_SIZE = (58, 58)

# for chord names
NAME_POS = (200, 10)
NAME_SIZE = (900, 240)

KEY_WORDS = ('no', 'maj', 'sus', 'add')

DISPLAY_SIZE = (238, 278)
FRET_SIZE = (156, 1240)
GRID_POS = (160, 240)
GRID_SIZE = (1080, 760)
# CHORD_NAME_SIZE = (1000, 320)

# chord dirs
CHORD_BACKGROUND_DIR = 'src/backgrounds/chord_background.png'
CHORD_DRAFT_DIR = "tmp/draft_chord.png"


# for strums
CELLS_CAP = 16

STRUM_IMAGE_WIDTH = 648
STRUM_IMAGE_HEIGHT = 198
STRUM_IMAGE_SIZE = (STRUM_IMAGE_WIDTH, STRUM_IMAGE_HEIGHT)

CELL_HEIGHT = 438
CELL_WIDTH = 310
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)

CELL_INDENT = 10

ORIGINAL_SIZE = (CELL_INDENT + CELLS_CAP * (CELL_WIDTH + CELL_INDENT), 3 * CELL_HEIGHT)

CELL_STATE_COMBO_BOX_ITEMS = (("Free", "PM", "Muted"), ('Clear', "Added"))

# COMPRESSION_RATIO_BY_WIDTH = 1   # don't use < 0.1
# COMPRESSION_RATIO_BY_HEIGHT = 1  # don't use < 0.16
# COMPRESSION_RATIO = (COMPRESSION_RATIO_BY_WIDTH, COMPRESSION_RATIO_BY_HEIGHT)

# strum dirs
HIDE_SUFFIX = "_hide"
CELL_IMAGES_DIR = "src/cell_images/"
STRUM_BACKGROUND_DIR = "src/backgrounds/strum_background.png"
STRUM_DRAFT_DIR = "tmp/draft_strum.png"
STRUMS_OUTPUT_FOLDER = "output/strums/"


# for tabs
DEFAULT_NUMBER_OF_LINES = 6
DEFAULT_NUMBER_OF_COLUMNS = 16

TAB_IMAGE_WIDTH = STRUM_IMAGE_WIDTH
TAB_IMAGE_HEIGHT = STRUM_IMAGE_HEIGHT
TAB_IMAGE_SIZE = STRUM_IMAGE_SIZE

TAB_ORIGINAL_SIZE = ORIGINAL_SIZE

TAB_TMP_IMAGE_WIDTH = 400
TAB_TMP_IMAGE_HEIGHT = 150
TAB_SIZE = (TAB_TMP_IMAGE_WIDTH, TAB_TMP_IMAGE_HEIGHT)

TAB_FONT_SIZE = 120

# tab dirs
TAB_BACKGROUND_DIR = "src/backgrounds/tab_background.png"
TAB_DRAFT_DIR = "tmp/draft_tab.png"
TAB_OUTPUT_FOLDER = "output/tabs/"
