name: Download Libs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Download libs
    runs-on: ubuntu-latest
    steps:
      - name: Clone JAR repository
        run: |
          git clone https://github.com/your-username/jar-repo.git
          cp jar-repo/your-library.jar libs/
